package com.harmadavtian.disneyapp.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity for storing content embeddings (vector representations).
 * 
 * This entity stores pgvector embeddings for semantic search across all content
 * types:
 * characters, movies, parks, attractions, and hints. Each embedding is
 * generated by
 * Google Gemini and enables RAG (Retrieval-Augmented Generation) queries.
 * 
 * Database table: content_embeddings
 * Migration: V4__add_rag_support.sql
 * 
 * Key features:
 * - Supports multiple content types via content_type discriminator
 * - Tracks model version for re-embedding when models upgrade
 * - Stores original text for reranking and debugging
 * - UNIQUE constraint prevents duplicate embeddings
 * 
 * @author Harma Davtian
 */
@Entity
@Table(name = "content_embeddings")
@Getter
@Setter
@NoArgsConstructor
public class ContentEmbedding {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "embedding_id")
    private Long embeddingId;

    /**
     * Content type discriminator: character, movie, park, attraction, hint.
     * Used for filtering results and smart re-embedding.
     */
    @Column(name = "content_type", nullable = false, length = 50)
    private String contentType;

    /**
     * Foreign key to content table (character_id, movie_id, park_id, etc.).
     * Not enforced at database level for flexibility across content types.
     */
    @Column(name = "content_id", nullable = false)
    private Long contentId;

    /**
     * Original text used to generate embedding.
     * Stored for reranking, debugging, and model version upgrades.
     */
    @Column(name = "text_content", nullable = false, columnDefinition = "TEXT")
    private String textContent;

    /**
     * pgvector embedding (768 dimensions for Gemini).
     * Stored as PostgreSQL vector type, converted manually in repository layer.
     * Marked @Transient because Hibernate doesn't natively support vector type.
     * 
     * Note: Repository queries handle conversion to/from PostgreSQL vector.
     */
    @Transient
    private float[] embedding;

    /**
     * Embedding model version (e.g., "gemini-text-embedding-004").
     * Tracks which model generated the embedding for version upgrades.
     */
    @Column(name = "model_version", nullable = false, length = 100)
    private String modelVersion = "gemini-text-embedding-004";

    /**
     * Creation timestamp (immutable).
     * Set automatically by database default (CURRENT_TIMESTAMP).
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Last update timestamp.
     * Updated automatically by database trigger
     * (update_content_embeddings_updated_at).
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Set creation timestamp before persist.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Set update timestamp before update.
     * Note: Database trigger also updates this, but JPA level ensures consistency.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
